[package]
name = "quops"
version = "0.1.0"
edition = "2021"

[dependencies]
quops_derive = { path = "crates/quops_derive" }
criterion = "0.7.0"
bitcode = "0.6.6"

[[bench]]
name = "quops"
harness = false

[profile.release]
codegen-units = 1
debug = true
